"""Parser for Perfetto trace files generated by JAX profiler."""

import gzip
import json
from dataclasses import dataclass
from pathlib import Path

from .decorators import PERFORMAX_PREFIX


@dataclass
class TraceEvent:
    """A single trace event from the profiler."""

    name: str
    duration_us: float  # Duration in microseconds


def _find_trace_file(trace_path: Path) -> Path | None:
    """Find the trace.json.gz file in the JAX profiler output directory.

    JAX creates trace files in a nested structure:
    <trace_path>/plugins/profile/<timestamp>/<hostname>.trace.json.gz

    Args:
        trace_path: Root path where jax.profiler.trace() writes output.

    Returns:
        Path to the trace file, or None if not found.
    """
    for path in trace_path.rglob("*.trace.json.gz"):
        return path
    return None


def parse_perfetto_trace(trace_path: Path) -> list[TraceEvent]:
    """Parse a Perfetto trace file and extract performax-tagged events.

    Args:
        trace_path: Path to the trace directory root.

    Returns:
        List of TraceEvent objects for functions decorated with @track.
    """
    trace_file = _find_trace_file(trace_path)

    if trace_file is None:
        return []

    with gzip.open(trace_file, "rt", encoding="utf-8") as f:
        data = json.load(f)

    events = []
    trace_events = data.get("traceEvents", [])

    for event in trace_events:
        if event.get("ph") != "X":
            continue

        name = event.get("name", "")
        if not name.startswith(PERFORMAX_PREFIX):
            continue

        func_name = name[len(PERFORMAX_PREFIX) :]
        duration_us = event.get("dur", 0)

        events.append(TraceEvent(name=func_name, duration_us=duration_us))

    return events
